name: Docker Build and Push

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Configure Maven settings for GitHub Packages
        env:
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${GITHUB_ACTOR}</username>
                <password>${PACKAGES_TOKEN}</password>
              </server>
              <server>
                <id>github-packages</id>
                <username>${GITHUB_ACTOR}</username>
                <password>${GITHUB_TOKEN}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Install Lombok
        run: mvn lombok:delombok

      - name: Build with Maven and Jib
        env:
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn clean package jib:build \
          -Djib.to.auth.username=${{ github.actor }} \
          -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }} \
          -Djib.allowInsecureRegistries=true \
          --settings ~/.m2/settings.xml

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}