name: Docker Build and Push

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Cache Jib layer
        uses: actions/cache@v3
        with:
          path: ~/.cache/google-cloud-tools-java/jib
          key: ${{ runner.os }}-jib-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-jib-

      - name: Configure Maven settings
        env:
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>${GITHUB_ACTOR}</username><password>${PACKAGES_TOKEN}</password></server><server><id>github-packages</id><username>${GITHUB_ACTOR}</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Build and push with Maven and Jib
        env:
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B clean package jib:build \
          -Djib.to.auth.username=${{ github.actor }} \
          -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }} \
          -Djib.allowInsecureRegistries=true \
          -Dgithub.repository.owner=${{ github.repository_owner }} \
          --settings ~/.m2/settings.xml